create table hosts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT,
	mac TEXT,
	ip TEXT,
	ports TEXT,
	hostName TEXT,
	hostType TEXT,
	os TEXT,
	osVersion TEXT,
	dependencies TEXT,
	exposedServices TEXT,
	status INTEGER,
	exposure INTEGER,
	internetAccess INTEGER,
	cpuCores INTEGER,
	ramGB INTEGER,
	storageGB INTEGER,
	usage TEXT,
	location TEXT,
	owners TEXT,
	access TEXT,
	connectsTo TEXT,
	createdBy TEXT NOT NULL,
	createdAt INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
	recordedAt INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP 
);