[package]
name = "port"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
actix-web = "4"
pistol = "2.0.4"
threadpool = "1.8.1"
