// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqls

import (
	"database/sql"
)

type Host struct {
	ID              interface{}    `json:"id"`
	Name            sql.NullString `json:"name"`
	Mac             sql.NullString `json:"mac"`
	Ip              sql.NullString `json:"ip"`
	Hostname        sql.NullString `json:"hostname"`
	Status          sql.NullInt64  `json:"status"`
	Exposure        sql.NullInt64  `json:"exposure"`
	Internetaccess  sql.NullInt64  `json:"internetaccess"`
	Os              sql.NullString `json:"os"`
	Osversion       sql.NullString `json:"osversion"`
	Ports           sql.NullString `json:"ports"`
	Usage           sql.NullString `json:"usage"`
	Location        sql.NullString `json:"location"`
	Owners          sql.NullString `json:"owners"`
	Dependencies    sql.NullString `json:"dependencies"`
	Createdat       sql.NullTime   `json:"createdat"`
	Createdby       sql.NullString `json:"createdby"`
	Recordedat      sql.NullTime   `json:"recordedat"`
	Access          sql.NullString `json:"access"`
	Connectsto      sql.NullString `json:"connectsto"`
	Hosttype        sql.NullString `json:"hosttype"`
	Exposedservices sql.NullString `json:"exposedservices"`
	Cpucores        sql.NullInt64  `json:"cpucores"`
	Ramgb           sql.NullInt64  `json:"ramgb"`
	Storagegb       sql.NullInt64  `json:"storagegb"`
}
